spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager_db
    username: taskmanageruser
    password: taskmanagerpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

server:
  port: 8080

jwt:
  secret: cG9ydG9mZm9saW9fdGVzdF9zZWNyZXRfa2V5X2Zvcl9kZXZfcHJvZmlsZQ==
  expiration-ms: 3600000

logging:
  level:
    org:
      springframework:
        security: DEBUG
